<?php

/*********************************************************************
* Extension configuration file for ext "doc_tut_templating".
*
* Generated by ext 25-06-2014 07:37 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Templating Tutorial',
  'description' => 'This document replaces the old templating tutorials like "Modern Template Building". The text is available at http://docs.typo3.org/typo3cms/TemplatingTutorial/.',
  'category' => 'doc',
  'shy' => 0,
  'version' => '0.7.0',
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'loadOrder' => '',
  'module' => '',
  'state' => 'beta',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearcacheonload' => 0,
  'lockType' => '',
  'author' => 'Official Documentation',
  'author_email' => 'documentation@typo3.org',
  'author_company' => '',
  'CGLcompliance' => '',
  'CGLcompliance_note' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '4.5.0-6.2.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  '_md5_values_when_last_written' => 'a:6:{s:12:"ext_icon.gif";s:4:"7277";s:38:"Resources/Private/Template/favicon.ico";s:4:"8718";s:50:"Resources/Private/Template/index-with-markers.html";s:4:"581e";s:37:"Resources/Private/Template/index.html";s:4:"7522";s:36:"Resources/Private/Template/style.css";s:4:"210a";s:46:"Resources/Private/Template/TypoScript-code.txt";s:4:"8596";}',
  'user' => 'docteam',
  'comment' => 'Raised compatibility to TYPO3 CMS 6.2',
);

?>