<?php

/*********************************************************************
* Extension configuration file for ext "doc_tut_templating".
*
* Generated by ext 25-06-2014 07:37 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Templating Tutorial',
  'description' => 'This document replaces the old templating tutorials like "Modern Template Building". The text is available at https://docs.typo3.org/typo3cms/TemplatingTutorial/.',
  'category' => 'doc',
  'version' => '0.7.0',
  'module' => '',
  'state' => 'beta',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearcacheonload' => 0,
  'author' => 'Official Documentation',
  'author_email' => 'documentation@typo3.org',
  'author_company' => '',
  'constraints' =>
  array (
    'depends' =>
    array (
      'typo3' => '4.5.0-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
);
