<?php

/*********************************************************************
* Extension configuration file for ext "doc_tut_templating".
*
* Generated by ext 12-05-2016 14:23 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Templating Tutorial',
  'description' => 'This distribution installs necessary resources for the Templating Tutorial, HTML template files and a basic page tree.',
  'category' => 'distribution',
  'version' => '8.7.0',
  'module' => '',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearcacheonload' => true,
  'author' => 'Official Documentation',
  'author_email' => 'documentation@typo3.org',
  'author_company' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '8.7.0-8.7.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'user' => 'docteam',
  'comment' => 'Corrected TypoScript template; added more content to the predefined data.',
);

?>